### ISSUE TITLE
Difference in AUC computed using causalnex and sklearn

### ISSUE THREAD

**Issue by vvrahul11** [quantumblacklabs/causalnex#108]
## Description
There is a difference between AUC computed using causalnex and AUC computed using sklearn.

## Context
In an experiment, I extracted the classification probability values that causalnex calculates and computed the AUC using sklearn (instead of using causalnex auc function.). There is a difference between AUC computed using causalnex and AUC computed using sklearn.

## Steps to Reproduce
Link to colab: https://colab.research.google.com/drive/1czogGy7rgHNgSfi7J96EcjwKe3ivPwwi?usp=sharing

## Expected Result
The output of sklean AUC and causalnex AUC should be the same

## Actual Result
The auc with the causalnex is 0.955 whereas, the auc with the scikitlearn is 0.912

## Your Environment
colab

* CausalNex version used (`pip show causalnex`): Version: 0.9.2
* Python version used (`python -V`): Python 3.7.10

**Comment by qbphilip** [comment]
Thanks for raising this and for sharing your colab notebook, very clear!

My intuition is that this is due to discretisation. 
Looking into the code we apply the same sklearn method but use a different "ground truth", i.e. discretised see [link to line](https://github.com/quantumblacklabs/causalnex/blob/4ad8b2f69ca4fa19cd2d67e1f6fc8aa743e1a4b2/causalnex/evaluation/evaluation.py#L99).

I did some quick look using your PR, I think the save choice is to use the raw sklearn output (=0.911 in your notebook).
There is an issue with the calculation of the AUC in the function that we will need to look into.

**Comment by qbphilip** [comment]
So, the current implementation is doing a `micro` aggergation as specified in its docstring, i.e. equivalent of running 
```
roc_auc_score(ground_truth, predictions, average="micro")
```
when providing both 0 and 1 columns.

However, as you spotted this is not consistent for binary data, will be fixed in the next release. I have added your notebook example as a unit test, thanks again for making it available!

In the meantime please use your proposed version with `sklearn.roc_auc_score`.

**Comment by vvrahul11** [comment]
Thank you @qbphilip for the prompt reply :)
