### ISSUE TITLE
Receiving OSerror while plotting the graph

### ISSUE THREAD

**Issue by SaiAditya2595** [quantumblacklabs/causalnex#177]
## Description
I am receiving OSerror while plotting the graph, I have tried to solve it by using some existing issues but it did not work for me. Can you help me on this?

```

OSError: Warning: node 'Gender', graph '' size too small for label
Warning: node 'Married', graph '' size too small for label
Warning: node 'Dependents', graph '' size too small for label
Warning: node 'Education', graph '' size too small for label
Warning: node 'Self_Employed', graph '' size too small for label
Warning: node 'ApplicantIncome', graph '' size too small for label
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* CausalNex version used (`pip show causalnex`): 0.11.0
* Python version used (`python -V`): 3.7.1
* Operating system and version: Windows 10 Pro

**Comment by ElisabethSesterHussQB** [comment]
Hello, thank you for reaching out. 
We are aware of common plotting issues on Windows machines. I understand those are warnings and not errors? This can be due to the visualisation package we are using in your current version of `causalnex` (0.11.0). We have released a new version of `causalnex` (0.12.0) this week where we replaced `pygraphviz` with `pyvis`. Please do try out the new version to see if this fixes your issue.
Please also note that we have stopped supporting `python 3.6 and 3.7` as they are no longer compatible with other required packages. Going forward, we advise you to install `python >= 3.8.`
Please feel free to reach out again if the issue continues to exist!
