### ISSUE TITLE
vis.show()  UnicodeEncodeError 

### ISSUE THREAD

**Issue by hutaohutc** [quantumblacklabs/causalnex#204]
I just run the tutorial code
```
import warnings
from causalnex.structure import StructureModel

warnings.filterwarnings("ignore")  # silence warnings

sm = StructureModel()
sm.add_edges_from([ ('health', 'absences'), ('health', 'G1') ])
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE

viz = plot_structure(
    sm,
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
)
viz.show("01_simple_plot.html")
```

but get error:
UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 230710: illegal multibyte sequence,
I have changed 2 win PCs,but get the same error

**Comment by kylelim-mckinsey** [comment]
Hi! 
this can be solved if you include the following code 
```
import os
os.environ["PYTHONIOENCODING"] = "utf8"

```

**Comment by hutaohutc** [comment]
@kylelim-mckinsey  thank you for your answer,but I use this code still get error.

UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 230710: illegal multibyte sequence
![image](https://github.com/quantumblacklabs/causalnex/assets/12443607/dc68891a-956f-482e-b4f6-bf688c8c3199)

**Comment by kylelim-mckinsey** [comment]
Let's use this. (I forgot to put the hyphen. It is 'utf-8'
```
import os
os.environ['PYTHONIOENCODING'] = 'utf-8'
```
So based on the error message, you are likely experiencing an encoding issue while using the Graphviz library in Python. This is typically due to differences in default encodings across systems. As the error message suggests, the issue might be related to the 'gbk' codec not being able to encode a specific character. 'gbk' is an encoding primarily used for simplified Chinese characters.

When Python interacts with your operating system or file system, it uses the system's default encoding. In Windows, it's often a variant of 'gbk'. It seems like the function you're using (which indirectly relies on Graphviz) is trying to write a character not compatible with the 'gbk' encoding.

**Comment by hutaohutc** [comment]
I am sorry ,I still get the same error..
![1684503060853](https://github.com/quantumblacklabs/causalnex/assets/12443607/0e5eb55f-3a38-4acd-869b-433ee3865420)

**Comment by GabrielAzevedoFerreiraQB** [comment]
I see. Thanks for the comment, Tau

**Comment by wxq0309** [comment]
![image](https://github.com/quantumblacklabs/causalnex/assets/44604781/f2a5424f-6e08-4aec-a057-b8859dd24d36)
![image](https://github.com/quantumblacklabs/causalnex/assets/44604781/63daceca-277c-4b1d-85ee-ed2ccf1549da)
I just ran the simplest demo, how can I solve this problem？

**Comment by kylelim-mckinsey** [comment]
Sorry,the image seems a little bit broken. Could you copy and paste the error message? Thank you!

**Comment by hutaohutc** [comment]
@GabrielAzevedoFerreiraQB It's worked! Thanks .
![image](https://github.com/quantumblacklabs/causalnex/assets/12443607/128e067e-1f16-431f-b752-c2f82bee322b)

**Comment by GabrielAzevedoFerreiraQB** [comment]
Awesome news. thanks!
