### ISSUE TITLE
log_uniform method for Discretiser

### ISSUE THREAD

**Issue by ogencoglu** [quantumblacklabs/causalnex#29]
## Description
`Discretiser` class is great. Would be quite helpful to have `log_uniform` method just like `uniform`. 

## Context
Often times attribute distributions is zero-inflated or somehow non-uniform / log-uniform.

## Possible Implementation
Same method utilized in `uniform` but first taking the logarithm of the data and reverting the percentiles back to normal scale.

**Comment by ogencoglu** [comment]
Btw, some visual formatting required to API docs of Discretiser. Bullet points in the parameters section is scrambled.

**Comment by ElisabethSesterHussQB** [comment]
Hello, thank you for the suggestion!

We looked into it and, indeed, depending on the data it does definitely make sense to transform it first before discretising it. However, we find that the choice of the transformation is highly dependent on the data (negative, zero-valued, non-zero, positive etc.). A log-transformation doesn’t always solve the problem of skewness and there is no “right” transformation that can be applied to all datasets.
The methods we have so far are very general and can be applied in any setting. Therefore, for skewed data, we would like to let the users decide which type of transformation they find most appropriate for their data rather than us providing one specific transformation.
The implementation is just as you say:

1. Transform the data to get closer to a normal distribution, e.g., log, Box-Cox, sqrt,…
2. Apply the `Discretiser` with `method=uniform`
3. Revert back the data to normal scale using the right inverse function

In many situations, it is also recommended to consult an expert and decide on a discretisation using the `fixed` method.

**Comment by oentaryorj** [comment]
Closing this for now. Feel free to raise a new issue if this feature request becomes crucial again.
