### ISSUE TITLE
Guidelines for improving accuracy of prediction

### ISSUE THREAD

**Issue by ajayrlogesh** [quantumblacklabs/causalnex#31]
Dear Team,

I have a continuous dataset with ~850 samples and 13 variables (including 1 target variable). I would like to identify the causes of the effect (target variable). The tutorial section has nicely explained steps to work with Causalnex. I am using causalnex 0.4.3.

Following this, the Structure Model has been created manually by including possible causes and relationships among them. All other steps as given in the tutorial have been followed and the model works well upto the step of Predictions (i.e. without any Errors). However, the final Evaluation metrics are not very good. For instance, the accuracy of Predictions vs Train_set and Predictions vs Test_set for minority/less majority classes are always somewhere around 60-70%. 

I have experimented with following different combination of modifications on model. 
1. As my dataset is largely imbalanced (class 1 : class 2 ~= 40:800), I used SMOTE technique for oversampling.
2. Increased/Decreased number of classes for all variables in Discretizer.
3. Used 'BDeu' bayes_prior along with varying equivalent_sample_size.
4. Different test_size in Train_test_split     

I am struggling to figure out the ways to optimize the model. I could not find any supportive material in Internet for the same. 

Are there any Guidelines or 'Best practices' of data pre-processing techniques and dataset requirements that particulary work for this library/model? Could you please suggest any troubleshooting methods to identify the cause of low accuracy/metrics?

Any ideas would be of great help! Thanks in Advance.

**Comment by t8ch** [comment]
Intuitively, I think your dataset may be too small given the number of observables (you seem to have "more than binary" variables, too). The documentation says that you should have at least 1000 samples (https://causalnex.readthedocs.io/en/latest/05_resources/05_faq.html)
.
However, maybe someone has a more elaborate idea...

**Comment by pjbqb** [comment]
Hi @ajayrlogesh ,

If I understand your sentence "Following this, the Structure Model has been created manually by including possible causes and relationships among them." correctly, you did not use NOTEARs, but manually defined the structure? Can I ask what the performance is like if you use NOTEARs?

There 's a couple of things that come to mind:

1) BNs, to be very honest, are not SUPER performant models; they're interpretable and often perform OK, but we're talking lower accuracies than methods like ensembles, DL, etc. [Just to manage expectations]

2) 850 samples with 1:20 class imbalance does sound quite hard to learn in a BN. In order to give it the best chance of working, I would try ensure you have a) remove any spurious parents going to your TV (else you don't have enough samples to fit good CPDs with), b) discretise the parent nodes that remain finely (to give best chance as possible to catch signal). I appreciate a) and b) are in some way a little contradictory, because if you discretise too finely, you risk not having enough data to fit the CPDs again...

3) The performance can be very subject to discretisation. If you can do it "without cheating" (i.e. makes business sense/it's still fair to do so and would likely generalise) can you choose a discretisation that maximises your performance by finding a 'decision boundary' between states?

Hope that helps :)
