### ISSUE TITLE
Do Intervention

### ISSUE THREAD

**Issue by ri3017** [quantumblacklabs/causalnex#49]
Hello,
Thank you very much for CausalNex! I am new to Bayesian Networks and I am trying to understand them. I have one question. If we set the distribution of the value of one feature to 1 like in the tutorial(100% students wanted to do a higher education) we will obtain a certain rate. Should the obtained rate be the same in the case  we set the distribution of the other possible value of the feature to 1? And why not? Moreover, setting only one value for all the instances in the dataset is equivalent to removing the certain feature?

**Comment by SteveLerQB** [comment]
Hi @ri3017,

This depends on your causal graph. If the other feature does not have causation on this feature, then yes the obtained rate will be the same. Let me give you an example for this:

Let's say we have a causal graph of   D<-A->B->C, intervening on B or A will affect the C result, but intervening on D **won't affect C** because there is **D does not cause C**.

On your second question, you are right to a certain extent, using the same example as before, a do intervention on both B and A is equivalent to *a do intervention on B* only

**Comment by oentaryorj** [comment]
Already addressed as above
